[2025-03-24T15:51:31.379-1000] {processor.py:186} INFO - Started process (PID=19149) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:51:31.379-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T15:51:31.380-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:51:31.380-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:51:31.390-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:51:31.390-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T15:51:31.390-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:51:31.390-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T15:51:31.390-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:51:31.414-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2025-03-24T15:53:05.541-1000] {processor.py:186} INFO - Started process (PID=20010) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:53:05.542-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T15:53:05.542-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:53:05.542-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:53:05.552-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:53:05.552-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T15:53:05.552-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:53:05.552-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T15:53:05.552-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:53:05.576-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-03-24T15:54:57.697-1000] {processor.py:186} INFO - Started process (PID=20457) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:54:57.698-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T15:54:57.698-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:54:57.698-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:54:57.708-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:54:57.707-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T15:54:57.708-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:54:57.708-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T15:54:57.708-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:54:57.730-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-03-24T15:56:46.939-1000] {processor.py:186} INFO - Started process (PID=20881) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:56:46.940-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T15:56:46.940-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:56:46.940-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:56:46.949-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:56:46.949-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T15:56:46.949-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:56:46.949-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T15:56:46.950-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:56:46.971-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-03-24T15:58:35.181-1000] {processor.py:186} INFO - Started process (PID=21303) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:58:35.183-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T15:58:35.184-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:58:35.184-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:58:35.192-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:58:35.192-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T15:58:35.192-1000] {logging_mixin.py:190} INFO - [2025-03-24T15:58:35.192-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T15:58:35.193-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T15:58:35.214-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-03-24T16:00:24.821-1000] {processor.py:186} INFO - Started process (PID=21741) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:00:24.822-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:00:24.822-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:00:24.822-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:00:24.831-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:00:24.831-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:00:24.831-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:00:24.831-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:00:24.831-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:00:24.853-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-03-24T16:02:33.420-1000] {processor.py:186} INFO - Started process (PID=22209) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:02:33.420-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:02:33.420-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:02:33.420-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:02:33.429-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:02:33.429-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:02:33.429-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:02:33.429-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:02:33.429-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:02:33.450-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:04:22.550-1000] {processor.py:186} INFO - Started process (PID=22619) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:04:22.550-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:04:22.550-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:04:22.550-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:04:22.559-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:04:22.559-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:04:22.559-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:04:22.559-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:04:22.559-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:04:22.581-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:06:07.676-1000] {processor.py:186} INFO - Started process (PID=23018) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:06:07.676-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:06:07.676-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:06:07.676-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:06:07.685-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:06:07.685-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:06:07.685-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:06:07.685-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:06:07.685-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:06:07.706-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:07:56.707-1000] {processor.py:186} INFO - Started process (PID=23471) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:07:56.707-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:07:56.708-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:07:56.707-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:07:56.716-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:07:56.716-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:07:56.716-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:07:56.716-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:07:56.716-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:07:56.737-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:09:50.385-1000] {processor.py:186} INFO - Started process (PID=23895) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:09:50.385-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:09:50.385-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:09:50.385-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:09:50.393-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:09:50.393-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:09:50.394-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:09:50.394-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:09:50.394-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:09:50.415-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:11:53.858-1000] {processor.py:186} INFO - Started process (PID=24396) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:11:53.859-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:11:53.859-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:11:53.859-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:11:53.867-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:11:53.867-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:11:53.868-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:11:53.867-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:11:53.868-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:11:53.889-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-03-24T16:13:54.374-1000] {processor.py:186} INFO - Started process (PID=24919) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:13:54.375-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:13:54.375-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:13:54.375-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:13:54.384-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:13:54.384-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:13:54.384-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:13:54.384-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:13:54.385-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:13:54.406-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-03-24T16:15:47.725-1000] {processor.py:186} INFO - Started process (PID=25368) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:15:47.725-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:15:47.725-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:15:47.725-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:15:47.734-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:15:47.734-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:15:47.734-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:15:47.734-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:15:47.735-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:15:47.756-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-03-24T16:17:35.918-1000] {processor.py:186} INFO - Started process (PID=25783) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:17:35.918-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:17:35.918-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:17:35.918-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:17:35.927-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:17:35.927-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:17:35.927-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:17:35.927-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:17:35.927-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:17:35.948-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:19:29.365-1000] {processor.py:186} INFO - Started process (PID=26238) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:19:29.366-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:19:29.366-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:19:29.366-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:19:29.374-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:19:29.374-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:19:29.374-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:19:29.374-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:19:29.374-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:19:29.396-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:21:19.369-1000] {processor.py:186} INFO - Started process (PID=26649) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:21:19.370-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:21:19.370-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:19.370-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:21:19.378-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:19.378-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:21:19.378-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:19.378-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:21:19.378-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:21:19.400-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:23:11.204-1000] {processor.py:186} INFO - Started process (PID=27087) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:23:11.204-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:23:11.204-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:11.204-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:23:11.213-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:11.213-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:23:11.213-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:11.213-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:23:11.213-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:23:11.234-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2025-03-24T16:25:04.475-1000] {processor.py:186} INFO - Started process (PID=27520) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:25:04.475-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:25:04.476-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:04.476-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:25:04.484-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:04.484-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:25:04.484-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:04.484-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:25:04.484-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:25:04.506-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:26:56.131-1000] {processor.py:186} INFO - Started process (PID=27940) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:26:56.131-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:26:56.132-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:56.132-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:26:56.140-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:56.140-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:26:56.140-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:56.140-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:26:56.140-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:26:56.162-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:28:44.557-1000] {processor.py:186} INFO - Started process (PID=28355) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:28:44.558-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:28:44.558-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:44.558-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:28:44.567-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:44.566-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:28:44.567-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:44.567-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:28:44.567-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:28:44.588-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:30:31.017-1000] {processor.py:186} INFO - Started process (PID=28757) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:30:31.017-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:30:31.017-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:31.017-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:30:31.026-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:31.026-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:30:31.026-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:31.026-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:30:31.026-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:30:31.047-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:32:21.200-1000] {processor.py:186} INFO - Started process (PID=29186) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:32:21.200-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:32:21.200-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:21.200-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:32:21.209-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:21.208-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:32:21.209-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:21.209-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:32:21.209-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:32:21.230-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-03-24T16:34:11.860-1000] {processor.py:186} INFO - Started process (PID=29615) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:34:11.860-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:34:11.861-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:11.861-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:34:11.869-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:11.869-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:34:11.869-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:11.869-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:34:11.869-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:34:11.890-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:36:00.150-1000] {processor.py:186} INFO - Started process (PID=30022) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:36:00.151-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:36:00.151-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:00.151-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:36:00.159-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:00.159-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:36:00.159-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:00.159-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:36:00.159-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:36:00.180-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-03-24T16:37:51.059-1000] {processor.py:186} INFO - Started process (PID=30447) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:37:51.060-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:37:51.060-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:51.060-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:37:51.070-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:51.070-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:37:51.070-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:51.070-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:37:51.070-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:37:51.092-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-03-24T16:39:48.550-1000] {processor.py:186} INFO - Started process (PID=30913) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:39:48.551-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:39:48.551-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:39:48.551-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:39:48.559-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:39:48.559-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:39:48.559-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:39:48.559-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:39:48.560-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:39:48.581-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-03-24T16:41:46.156-1000] {processor.py:186} INFO - Started process (PID=31366) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:41:46.156-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:41:46.157-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:41:46.156-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:41:46.165-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:41:46.165-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:41:46.165-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:41:46.165-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:41:46.165-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:41:46.187-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-03-24T16:43:39.608-1000] {processor.py:186} INFO - Started process (PID=31800) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:43:39.610-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:43:39.610-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:43:39.610-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:43:39.618-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:43:39.618-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:43:39.619-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:43:39.618-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:43:39.619-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:43:39.640-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-03-24T16:45:28.165-1000] {processor.py:186} INFO - Started process (PID=32219) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:45:28.166-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:45:28.166-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:45:28.166-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:45:28.174-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:45:28.174-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:45:28.174-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:45:28.174-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:45:28.175-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:45:28.196-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-03-24T16:47:20.482-1000] {processor.py:186} INFO - Started process (PID=32660) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:47:20.484-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:47:20.484-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:47:20.484-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:47:20.493-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:47:20.492-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:47:20.493-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:47:20.493-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:47:20.493-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:47:20.514-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-03-24T16:49:18.570-1000] {processor.py:186} INFO - Started process (PID=33216) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:49:18.571-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:49:18.571-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:49:18.571-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:49:18.580-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:49:18.580-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:49:18.580-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:49:18.580-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:49:18.580-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:49:18.602-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-24T16:51:13.404-1000] {processor.py:186} INFO - Started process (PID=33649) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:51:13.405-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:51:13.405-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:51:13.405-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:51:13.414-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:51:13.414-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:51:13.414-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:51:13.414-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:51:13.414-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:51:13.436-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-24T16:53:09.128-1000] {processor.py:186} INFO - Started process (PID=34085) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:53:09.128-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:53:09.129-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:53:09.129-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:53:09.138-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:53:09.138-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:53:09.139-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:53:09.138-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:53:09.139-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:53:09.161-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-24T16:55:03.775-1000] {processor.py:186} INFO - Started process (PID=34511) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:55:03.776-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:55:03.776-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:55:03.776-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:55:03.784-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:55:03.784-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:55:03.784-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:55:03.784-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:55:03.784-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:55:03.805-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T16:56:55.207-1000] {processor.py:186} INFO - Started process (PID=34933) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:56:55.207-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:56:55.207-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:56:55.207-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:56:55.216-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:56:55.216-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:56:55.216-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:56:55.216-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:56:55.216-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:56:55.237-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T16:58:43.284-1000] {processor.py:186} INFO - Started process (PID=35349) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:58:43.284-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T16:58:43.284-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:58:43.284-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:58:43.293-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:58:43.293-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T16:58:43.293-1000] {logging_mixin.py:190} INFO - [2025-03-24T16:58:43.293-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T16:58:43.293-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T16:58:43.314-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:00:36.816-1000] {processor.py:186} INFO - Started process (PID=35777) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:00:36.817-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:00:36.817-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:00:36.817-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:00:36.825-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:00:36.825-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:00:36.825-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:00:36.825-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:00:36.825-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:00:36.847-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:02:35.954-1000] {processor.py:186} INFO - Started process (PID=36233) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:02:35.954-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:02:35.954-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:02:35.954-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:02:35.963-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:02:35.963-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:02:35.963-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:02:35.963-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:02:35.963-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:02:35.984-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:04:30.035-1000] {processor.py:186} INFO - Started process (PID=36655) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:04:30.036-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:04:30.036-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:04:30.036-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:04:30.044-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:04:30.044-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:04:30.044-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:04:30.044-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:04:30.044-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:04:30.065-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:06:20.460-1000] {processor.py:186} INFO - Started process (PID=37072) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:06:20.460-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:06:20.460-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:06:20.460-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:06:20.468-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:06:20.468-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:06:20.469-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:06:20.468-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:06:20.469-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:06:20.489-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:08:09.152-1000] {processor.py:186} INFO - Started process (PID=37520) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:08:09.152-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:08:09.152-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:08:09.152-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:08:09.161-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:08:09.161-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:08:09.161-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:08:09.161-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:08:09.161-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:08:09.181-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-24T17:10:01.016-1000] {processor.py:186} INFO - Started process (PID=37947) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:10:01.016-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:10:01.016-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:10:01.016-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:10:01.024-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:10:01.024-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:10:01.025-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:10:01.025-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:10:01.025-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:10:01.045-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-24T17:11:49.417-1000] {processor.py:186} INFO - Started process (PID=38360) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:11:49.417-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:11:49.417-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:11:49.417-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:11:49.426-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:11:49.426-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:11:49.426-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:11:49.426-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:11:49.426-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:11:49.447-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:13:36.643-1000] {processor.py:186} INFO - Started process (PID=38771) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:13:36.643-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:13:36.644-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:13:36.644-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:13:36.652-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:13:36.652-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:13:36.652-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:13:36.652-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:13:36.652-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:13:36.673-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:15:26.304-1000] {processor.py:186} INFO - Started process (PID=39186) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:15:26.305-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:15:26.305-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:15:26.305-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:15:26.313-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:15:26.313-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:15:26.313-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:15:26.313-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:15:26.313-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:15:26.334-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:17:16.904-1000] {processor.py:186} INFO - Started process (PID=39603) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:17:16.905-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:17:16.905-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:17:16.905-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:17:16.913-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:17:16.913-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:17:16.913-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:17:16.913-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:17:16.914-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:17:16.934-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:19:04.976-1000] {processor.py:186} INFO - Started process (PID=40033) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:19:04.977-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:19:04.977-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:19:04.977-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:19:04.986-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:19:04.986-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:19:04.987-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:19:04.986-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:19:04.987-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:19:05.007-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-24T17:20:58.620-1000] {processor.py:186} INFO - Started process (PID=40473) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:20:58.621-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:20:58.621-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:20:58.621-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:20:58.630-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:20:58.630-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:20:58.630-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:20:58.630-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:20:58.630-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:20:58.651-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-24T17:22:49.025-1000] {processor.py:186} INFO - Started process (PID=40922) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:22:49.026-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:22:49.026-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:22:49.026-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:22:49.035-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:22:49.035-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:22:49.035-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:22:49.035-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:22:49.035-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:22:49.056-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-24T17:24:42.467-1000] {processor.py:186} INFO - Started process (PID=41349) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:24:42.468-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:24:42.468-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:24:42.468-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:24:42.478-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:24:42.478-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:24:42.478-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:24:42.478-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:24:42.478-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:24:42.501-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-24T17:26:42.001-1000] {processor.py:186} INFO - Started process (PID=41879) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:26:42.002-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:26:42.002-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:26:42.002-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:26:42.011-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:26:42.011-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:26:42.011-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:26:42.011-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:26:42.011-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:26:42.033-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-24T17:28:37.417-1000] {processor.py:186} INFO - Started process (PID=42358) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:28:37.417-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:28:37.417-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:28:37.417-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:28:37.426-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:28:37.425-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:28:37.426-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:28:37.426-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:28:37.426-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:28:37.447-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:30:30.263-1000] {processor.py:186} INFO - Started process (PID=42823) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:30:30.263-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:30:30.263-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:30:30.263-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:30:30.272-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:30:30.271-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:30:30.272-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:30:30.272-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:30:30.272-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:30:30.292-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-24T17:32:33.610-1000] {processor.py:186} INFO - Started process (PID=43355) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:32:33.611-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T17:32:33.611-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:32:33.611-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:32:33.620-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:32:33.620-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T17:32:33.620-1000] {logging_mixin.py:190} INFO - [2025-03-24T17:32:33.620-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T17:32:33.620-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T17:32:33.641-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
