[2025-03-24T17:25:45.334-1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T17:25:45.337-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:25:39.747196+00:00 [queued]>
[2025-03-24T17:25:45.338-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:25:39.747196+00:00 [queued]>
[2025-03-24T17:25:45.338-1000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-24T17:25:45.341-1000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): train_model_task> on 2025-03-25 03:25:39.747196+00:00
[2025-03-24T17:25:45.346-1000] {standard_task_runner.py:72} INFO - Started process 41605 to run task
[2025-03-24T17:25:45.348-1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'titanic', 'train_model_task', 'manual__2025-03-25T03:25:39.747196+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/titanic_airflow.py', '--cfg-path', '/var/folders/m_/z_1_g7ln0f54m3f57y9mjg440000gn/T/tmpyk6l4iqg']
[2025-03-24T17:25:45.349-1000] {standard_task_runner.py:105} INFO - Job 16: Subtask train_model_task
[2025-03-24T17:25:45.362-1000] {task_command.py:467} INFO - Running <TaskInstance: titanic.train_model_task manual__2025-03-25T03:25:39.747196+00:00 [running]> on host mac.localdomain
[2025-03-24T17:25:45.377-1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T03:25:39.747196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T03:25:39.747196+00:00'
[2025-03-24T17:25:45.377-1000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T17:25:45.378-1000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T17:25:45.378-1000] {logging_mixin.py:190} INFO - Current task name:train_model_task state:running start_date:2025-03-25 03:25:45.337342+00:00
[2025-03-24T17:25:45.378-1000] {logging_mixin.py:190} INFO - Dag name:titanic and current dag run status:running
[2025-03-24T17:25:45.378-1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T17:25:45.557-1000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 52, in train_model_task
    register_model = np.nan
                     ^^
NameError: name 'np' is not defined
[2025-03-24T17:25:45.561-1000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T17:25:45.562-1000] {logging_mixin.py:190} INFO - Task start:2025-03-25 03:25:45.337342+00:00 end:2025-03-25 03:25:45.561723+00:00 duration:0.224381
[2025-03-24T17:25:45.562-1000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): train_model_task> dag:<DAG: titanic> dagrun:<DagRun titanic @ 2025-03-25 03:25:39.747196+00:00: manual__2025-03-25T03:25:39.747196+00:00, state:running, queued_at: 2025-03-25 03:25:39.751581+00:00. externally triggered: True>
[2025-03-24T17:25:45.562-1000] {logging_mixin.py:190} INFO - Failure caused by name 'np' is not defined
[2025-03-24T17:25:45.562-1000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic, task_id=train_model_task, run_id=manual__2025-03-25T03:25:39.747196+00:00, execution_date=20250325T032539, start_date=20250325T032545, end_date=20250325T032545
[2025-03-24T17:25:45.566-1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T17:25:45.566-1000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task train_model_task (name 'np' is not defined; 41605)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 52, in train_model_task
    register_model = np.nan
                     ^^
NameError: name 'np' is not defined
[2025-03-24T17:25:45.607-1000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T17:25:45.612-1000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T17:25:45.612-1000] {local_task_job_runner.py:245} INFO - ::endgroup::
